### ISSUE TITLE
Update examples to use Docker v4

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/examples#1438]
## Issue details

As with pulumi/templates#567, we should update examples to use the latest Docker provider.
```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/examples/issues/1591
- [ ] https://github.com/pulumi/examples/issues/1592
- [ ] https://github.com/pulumi/examples/issues/1593
- [ ] https://github.com/pulumi/examples/issues/1594
```

**Comment by scottslowe** [comment]
The following TypeScript examples appear to be affected:

`azure-ts-containerapps`
`classic-azure-ts-cosmosapp-component`
`gcp-ts-docker-grc-cloudrun`
`docker-ts-multi-container-app`
`gcp-ts-cloudrun`
`classic-azure-ts-aks-keda`
`google-native-ts-k8s-python-postgresql`
`gcp-ts-k8s-ruby-on-rails-postgresql`
`google-native-ts-k8s-ruby-on-rails-postgresql`
`classic-azure-ts-appservice-springboot`
`azure-ts-appservice-docker`
`aws-ts-hello-fargate`

The following Go examples seem to be affected:

`azure-go-appservice-docker`
`azure-go-containerapps`

The following Python examples seem to be affected:

`docker-py-multi-container-app`
`azure-py-containerapps`
`azure-py-appservice`
`aws-py-voting-app`
`aws-py-django-voting-app`

This list is not necessarily complete, but it is a reasonable starting point.

**Comment by scottslowe** [comment]
It's also unclear to me how https://github.com/pulumi/pulumi-awsx/issues/1010 may affect this

**Comment by rshade** [comment]
This has been completed.
